extends Button
@onready var reset: Button = $"../Reset"
@onready var cs: Button = $"../TabContainer/门派/CS"
@onready var hs: Button = $"../TabContainer/门派/HS"
@onready var fe: Button = $"../TabContainer/门派/FE"
@onready var dx: Button = $"../TabContainer/门派/DX"
@onready var elixir: Button = $"../TabContainer/副职/Elixir"
@onready var fulu: Button = $"../TabContainer/副职/Fulu"
@onready var music: Button = $"../TabContainer/副职/Music"
@onready var paint: Button = $"../TabContainer/副职/Paint"
@onready var formation: Button = $"../TabContainer/副职/Formation"
@onready var plant: Button = $"../TabContainer/副职/Plant"
@onready var fortune: Button = $"../TabContainer/副职/Fortune"
@onready var detail_mode: CheckButton = $"../DetailMode"

func _ready() -> void:
	button_pressed = Global.language
	if button_pressed == true:
		reset.text = "Reset"
		cs.text = "Cloud Spirit Sword Sect"
		hs.text = "Hepstar Pavilion"
		fe.text = "Five Elements Alliance"
		dx.text = "Duan Xuan Sect"
		elixir.text = "Elixirist"
		fulu.text = "Fuluist"
		music.text = "Musician"
		paint.text = "Painter"
		formation.text = "Formation Master"
		plant.text = "Plant Master"
		fortune.text = "Fortune Teller"
		detail_mode.text = "Counter"
	else:
		reset.text = "初始化"
		cs.text = "云灵剑宗"
		hs.text = "七星阁"
		fe.text = "五行道盟"
		dx.text = "锻玄宗"
		elixir.text = "炼丹师"
		fulu.text = "符咒师"
		music.text = "琴师"
		paint.text = "画师"
		formation.text = "阵法师"
		plant.text = "灵植师"
		fortune.text = "命理师"
		detail_mode.text = "计数"
		
func _on_toggled(toggled_on: bool) -> void:
	Global.language = toggled_on
	if toggled_on == true:
		reset.text = "Reset"
		cs.text = "Cloud Spirit Sword Sect"
		hs.text = "Hepstar Pavilion"
		fe.text = "Five Elements Alliance"
		dx.text = "Duan Xuan Sect"
		elixir.text = "Elixirist"
		fulu.text = "Fuluist"
		music.text = "Musician"
		paint.text = "Painter"
		formation.text = "Formation Master"
		plant.text = "Plant Master"
		fortune.text = "Fortune Teller"
		detail_mode.text = "Counter"
	else:
		reset.text = "初始化"
		cs.text = "云灵剑宗"
		hs.text = "七星阁"
		fe.text = "五行道盟"
		dx.text = "锻玄宗"
		elixir.text = "炼丹师"
		fulu.text = "符咒师"
		music.text = "琴师"
		paint.text = "画师"
		formation.text = "阵法师"
		plant.text = "灵植师"
		fortune.text = "命理师"
		detail_mode.text = "计数"
		
